### ISSUE TITLE
Failed to enumerate dedicated GPU when default adapter is intergrated GPU

### ISSUE THREAD

**Issue by qytek** [Microsoft/DXUT#6]
File: DXUTDevice11.cpp, Function: CD3D11Enumeration::Enumerate, Line:154
Always failed to EnumerateOutputs of Dedicated GPU, which makes creation on dedicated gpu not possible,
also, when laptop has both intergrated GPU and dedicated GPU, create a device on dedicated GPU will require back buffer format of "DXGI_FORMAT_R10G10B10A2_UNORM", otherwise SwapChain::Present will break, this should be a default setting when user want to create a dedicated device.

Hope this functionality will be a global setting.

References: 
UnrealEngine4, WindowsD3D11Device.cpp
FD3D11DynamicRHIModule::FindAdapter()

**Comment by walbourn** [comment]
Can you please provide more detail here on your repro? What is the feature level of your GPU?

Do you have a specific code fix in mind?

All Direct3D feature level devices are required to support both ``DXGI_FORMAT_R8G8B8A8_UNORM_SRGB`` and ``DXGI_FORMAT_R8G8B8A8_UNORM``. Support for HDR formats ``DXGI_FORMAT_R16G16B16A16_FLOAT`` and ``DXGI_FORMAT_R16G16B16A16_FLOAT``  require Feature level 10.0 or greater.

**Comment by qytek** [comment]
Here is my specs:
Windows 10 64bits, Intel Grpahics HD 4600, nvidia 980M
Os is upgrated from Windows 8.1;
On old windows 8.1, everything runs correctly. I can swich device creation on both GPU using 'nvidia contorl panel', or programmingly tells DXGI using a dedicated adapter.
And after upgrading to Windows 10, when i switch on 'using nvidia gpu' in 'nvidia control panel', everything that use DirectX11 will not render at all. Including .net framework,
'Visual Studio Code', and all the sampler code from nvidia/intel/amd developer sites,all the rendering window will be black the whole time.
So I try to use the programming way to find out why, here is what i found out
1. DXUT cannot find dedicated gpu (on Windows 10), because EnumOutputs failed
2. Skip that part, and we can create a device on decicated GPU, but, SwapChain::Present will throw a _comptr related error.
3. Set the back buffer format from rgba8888, or agbr8888, to r10g10b10a2 will finally works, which I looked into UnrealEngine4, they have solved the problem.

And I think this is the wrong place to fire this issue, and I don't quite say this is a bug of DXUT or Windows 10, consider that DirectX12 is more like the first class api
for windows 10.
Still, it will be nice to modify the code to support laptops that runs on Windows 10.

Here is what i have in mind about code fix:
1. use a better way to EnumOutputs of adapter
2. use a better way to validate all back buffer formats before set a default( because, yes, you can use rgba8888 in my case, 
but SwapChain::Present will throw an exeption, and return a S_OK the same time, which blows my mind )
3. DXGI is really chaos among all the versions, could be nice to have a abstraction layer on top of that, so we can easily support from windows vista to windows 10.

**Comment by walbourn** [comment]
Basically you are having problems with the NVIDIA "Optimus" technology, which is not part of the OS. First make sure you install the least NVIDIA driver package and report problems to NVIDIA. They manipulate the DXGI adapter enumeration for this, which is the root of your problems.

1. What "better way" did you have in mind?
2. The DirectX Runtime is free to use exception handling internally but doesn't leak them. If you are getting ``S_OK``, any exception the debugger caught was already handled. It's an implementation detail, not a bug.
3. The vast majority of DXUT's adapter enumeration stuff is largely irrelevant for modern platforms. It's a carry-over from the Direct3D 9 days. See [DeviceResources](https://github.com/Microsoft/DirectXTK/wiki/DeviceResources) for a more modern way to do it that is simple.

**Comment by qytek** [comment]
I didn't explain clearly enough.
Yes, I know this is maybe an issue of NVIDIA Optimus, and yes, I figure out how to create an directx 11 device on dedicated GPU using DXUT.
But, DXUT is the most standard code base of directx 11 samplers, and maybe the the most imporatant one( intel/amd/nvidia samplers are all based on top of it ), the purpose of DXUT is to illustrate how to use DirectX 11 in a real world application. There are a lot of customers who has Alienware laptops and upgrated their OS from Windows 8.1, and they will meet the same problem, and some of them already tried to install the latest drivers and failed to run directx 11 applications( http://forum.notebookreview.com/threads/windows-10-and-nvidia-980m-gtx-upgrades-for-alienware-m17x-r4-without-optimus-working-great.777145/ )
As developers, we cannot throw the problem to the users, expect them geek enough to know how to disable intergrated gpu in the BIOS.
Here is what i thought, not only just about DXUT.
1. What if dxgi_adapter EnumOutputs and dxdiag(32bits or 64bits ) both failed to find outputs of dedicated GPU, and the driver informations ( which is my case, and all the alienware guys ) ? Can the applicaton provide more detailes to programmers, or to users?
2. What if a back buffer format that should always be valid, but acturally failed to present, how can the application knows about the detailes
3. I'm temporarily fixing the problem as I mensioned, "Skip EnumOutputs failed, Skip default back format validation, using r10g10b10a2", so the players of our game will be able to use dedicated GPU on Windows 10, without knowing anything to hack into BIOS.

And thanks for the link of DeviceResource, I will check that out later.

**Comment by walbourn** [comment]
1. if an application can't find a specific output, just use the default adapter. There's no other logical option.

2. Invalid backbuffers formats will fail to create. Direct3D Hardware Feature Levels spell out what you as the developer need to design to. I don't know that you mean by "fails to present". Is the monitor out of sync? are you talking about full-screen mode?

3. r10g10b10a2 can only be counted on if you require a minimum of Feature Level 10.0 or higher.

All that said, using DXUT as the basis of a production game engine is not recommended. It's designed for samples and prototypes.
