### ISSUE TITLE
DXUTGetDXGIColorChannelBits

### ISSUE THREAD

**Issue by JujiPL** [Microsoft/DXUT#7]
I would suggest one idea.
**DXUTGetDXGIColorChannelBits**, **BitsPerPixel** and other **BitsPerPixel** are functions doing almost the same.
Maybe there should be one function instead of three present or more.

P. S.
In my opinion, the function should have its own cpp files common for all calls.

_Thank you for the great framework._

**Comment by walbourn** [comment]
``DXUTGetDXGIColorChannelBits`` actually does something quite distinct from ``BitsPerPixel``. For example, given the input format of ``DXGI_FORMAT_R8G8B8A8_UNORM`` the DXUT function returns 8 while the BitsPerPixel function returns 32.

The DDSTextureLoader, WICTextureLoader, and ScreenGrab files are all intended to be standalone so they do have some replicated code in them.
